meta_product_name: "WeKite"
meta_title: "WeKite | Best spots in the world"
meta_description: "Find the best spots for the next 7 days"
meta_image: "cover.png"
twitter_account: "@product_twitter_account"
