# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b49f84cb8839bf13c04d56f5a7d7fb2b4b0526b870af32239a8538d06afbf3aed3c204d4230060a3e3eafd2f04f03c33620bda079ce4a79008b2ac54107fa5d9

test:
  secret_key_base: 00f2236db42071fb73791ff17b7ed5c5d5010d1f5fedfd6c462c20de403bf44b316889f463f01a2d5f33cd412fa1fc391676f93df2263b1cbacb5f7f5145b84c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
